theochem/grid

setup.py
This is required to fix automatic release work.
=> Fix get_version() of setup.py to get right version

grid/grid/rtransform.py, grid/grid/test/test_rtransform.py
1. Tranlate rtransform.cpp to rtransform.py
2. Update test_rtransform for the new pure python version
=> Translated rtransform module

grid/grid/becke.py, grid/grid/test/test_becke.py
File becke.py translate from cpp to py, and check the test
Change description in becke.py
Becke working in python
Becke and test_becke with PEP8 style and running well
Becke translate to python
=> Added Becke weights in python

grid/grid/becke.py, setup.py
=> Minor Updates

grid/grid/test/test_becke.py, tox.ini
=> Small Fixes

src/grid/grid.py, src/grid/onedgrid.py, src/grid/tests/test_grid.py, src/grid/tests/test_init.py, src/grid/tests/test_onedgrid.py, tox.ini
Add basic Grid class as OneDGrid with points and weights.
Add a basic module to generate different kind of 1dgrid according to the notes.
=> Add basic oned grid class with basic functions

src/grid/atomic_grid.py, src/grid/grid.py, src/grid/lebedev.py, src/grid/rtransform.py, src/grid/tests/test_atomic_grid.py, src/grid/tests/test_grid.py, src/grid/tests/test_lebedev_laikov.py, src/grid/tests/test_onedgrid.py, src/grid/tests/test_transform.py, tox.ini
Add atomic grid, change the input as Paul's notes
=> Atomicgrid

README.md, src/grid/atomic_grid.py
1. Update doc for keyword-only arguments
2. Update README.md
=> Update docs in atomicgrid

README.md
Update Readme and test azure pipeline tests
=> Update Readme for azure pipeline.

.gitignore
Just a minor change. Those files easily appear when installing etc.
=> Add few missing items to gitignore

src/grid/atomic_grid.py
=> Clarifications of AtomicGrid.__init__ docstring

src/grid/atomic_grid.py, src/grid/basegrid.py, src/grid/becke.py, src/grid/interpolate.py, src/grid/lebedev.py, src/grid/molgrid.py, src/grid/onedgrid.py, src/grid/rtransform.py, src/grid/tests/test_interpolate.py, src/grid/utils.py
=> Fix typos in several modules

src/grid/atomic_grid.py, src/grid/interpolate.py, src/grid/tests/test_atomic_grid.py, src/grid/tests/test_interpolate.py
1. Add deriv arg in interpolate function.
2. Update tests for deriv tests and new atomic_grid method
3. Update docstyle
=> Add derivation function.

src/grid/onedgrid.py
1. Add equations
2. Add interval for onedgrid
=> Add docs for clarify usage for some onedgrid

setup.py, src/grid/atomic_grid.py, src/grid/interpolate.py, src/grid/ode.py, src/grid/tests/test_atomic_grid.py, src/grid/tests/test_interpolate.py, src/grid/tests/test_ode.py, src/grid/tests/test_transform.py
1. Add high level function for solve bvp with scipy
2. Add transformation support for bvp
=> Add generic ODE boundary value problem solver with transformation

README.md
Add acknowledgement to Canarie etc.
=> Update README for acknowledgement

src/grid/molgrid.py, src/grid/rtransform.py, src/grid/tests/test_interpolate.py, src/grid/tests/test_molgrid.py, src/grid/tests/test_radial.py, src/grid/tests/test_transform.py
This PR is meant to share some of the changes @tovrstra and I was thinking about. I will be pushing more commits in the coming days. Please let us know what you think.
=> Refactoring 

src/grid/interpolate.py, src/grid/ode.py, src/grid/poisson.py, src/grid/tests/test_interpolate.py, src/grid/tests/test_poisson.py, src/grid/tests/test_transform.py
Add poisson solver to grid.
Add tests for poisson solver
Add interpolation method for poisson solver
=> Add poisson solver to grid

src/grid/becke.py, src/grid/molgrid.py, src/grid/tests/test_becke.py, src/grid/tests/test_molgrid.py
This is not perfectly polished probably, but I wanted to share it asap to get your opinion before spending more time on it.
=> Refactor Molgrid & BeckeWeights

src/grid/basegrid.py, src/grid/onedgrid.py, src/grid/rtransform.py, src/grid/tests/test_interpolate.py, src/grid/tests/test_molgrid.py, src/grid/tests/test_poisson.py, src/grid/tests/test_radial.py, src/grid/tests/test_transform.py
Remove grid in onedgrid and transform files
Add negative inf value check
Update math equations in transform
=> Doc update

src/grid/tests/test_onedgrid.py
=> Oned check

src/grid/atomic_grid.py, src/grid/tests/test_atomic_grid.py, src/grid/tests/test_interpolate.py, src/grid/tests/test_lebedev_laikov.py, src/grid/tests/test_onedgrid.py, src/grid/tests/test_poisson.py, src/grid/tests/test_transform.py
1. Use py3.6 suggested @ op to replace np.dot
=> Use @ to replace np.dot for better readability

src/grid/basegrid.py
Very minor correction. I didn't want to include in the other PR I just made because it is not really related.
=> Fix a small typo

src/grid/basegrid.py, src/grid/tests/test_grid.py, src/grid/tests/test_molgrid.py
These minor changes were useful/needed when prototyping denspart.
=> Add indices property to subgrid

setup.py, src/grid/atomic_grid.py, src/grid/rtransform.py, src/grid/tests/test_atomic_grid.py
1. Update setup with scipy dependency to 1.14
2. Update random().as_dcm() to random().as_matrix()
3. Silence runtimewarning when construct grid
=> Fix warning in code

src/grid/molgrid.py, src/grid/tests/test_molgrid.py
1. Allow molgrid to construct molgrid with predefined grid scheme
2. Add complete test for molgrid make grid with different setting
=> Add molgrid make_grid classmethod

src/grid/onedgrid.py, src/grid/rtransform.py, src/grid/tests/test_interpolate.py, src/grid/tests/test_rtransform.py, src/grid/tests/test_transform.py
1. Add domain and codomain property to each transform
2. Change tests accordingly
=> Add domain & codomain to transform

src/grid/becke.py, src/grid/tests/test_becke.py
1. Separate q P_A calculation from becke weights
evaluation
2. Add a new compute_weight outer loop for compute
becke weights for each section of points
=> Add a new becke weight function

src/grid/atomgrid.py, src/grid/lebedev.py, src/grid/tests/test_atomgrid.py, src/grid/tests/test_lebedev.py
1. Using to dictionary for fast lebedev lookup
2. Fix some potential error-prone codes
=> Update lebedev grid generating algorithm

src/grid/atomgrid.py, src/grid/tests/test_utils.py, src/grid/utils.py
1. Reconstrcut convert_cart_to_sph method(function)
2. Add accuracy tests
=> Add convert_cart_to_sph into utils #66

src/grid/__init__.py, src/grid/atomgrid.py, src/grid/lebedev.py, src/grid/tests/test_lebedev.py
1. Add cache to lebedev grid incase repetitive I/O
2. Add cache contents test
3. Remove redundant cache in atomic level
=> Add global cache_dict to store loaded npz file #67

src/grid/basegrid.py
1. remove `=` sign when comparing values
2. Adjust f-string for better error message
=> Fix domain limit problem #132

src/grid/atomgrid.py, src/grid/tests/test_atomgrid.py
Add function to generate spherical harmonics
Add function to fit radial value into cubic splines
Add function to interpolate points on splines
=> Add spherical harmonics and interpolation

src/grid/onedgrid.py
Small pull request that fixes the domain issues from [0, 1] to [-1, 1] for the RectangleRule and RectangleRuleEndpoints and replaced [-1:1] with [1, 1]
=> Fix documentation domain issues in onedgrids

doc/notebooks/JCP_Paper.ipynb, src/grid/utils.py
I believe there is a small typo in the docstring for the real spherical harmonics in the `generate_real_spherical_harmonics` function. This PR simply adds the missing square root.
=> Fixed error in real spherical harmonics docstring equation

doc/notebooks/JCP_Paper.ipynb
Added the badge to open the notebook in Colab.
=> Add open in colab badge

src/grid/angular.py, src/grid/atomgrid.py, src/grid/basegrid.py, src/grid/tests/test_angular.py, src/grid/tests/test_atomgrid.py
The commit messages should be self-explanatory. I talked about 5e4323095b91017f516aff346c023dfb17e7ad21 with @marco-2023 and @PaulWAyers yesterday, and they also agreed that we need an argument that supports more than just two angular grid methods. Feel free to let me know what you think.
=> Refactor Angular Grid

.github/workflows/pypi_release.yaml, .github/workflows/pytest.yaml, README.md, pyproject.toml
Givent that `qc-grid` is taken, we will use `qc-grid` as a temporary solution.
=> Use `qc-grids` as temporary solution
