theochem/grid

- .travis.yml
- tools/conda.recipe/meta.yaml
- All run requirements have to be included in host requirements.
- Run requirements should be consistent with setup.py
This should make it possible again to release versions of grid.
> Fix package build on Conda

- grid/grid/__init__.py
- grid/grid/test/test_uniform.py
- grid/grid/uniform.py
1. Translate cpp `UnifromGrid` to python
2. Remove `pbc` from `UniformGrid`
3. Have grid.grid.test_uniform use python `UnifromGrid`
4. Comment `get_ranges_rcut` tests; the `get_ranges_rcut` method will be implemented if needed at a later stage.
> Translate UniformGrid

- src/grid/becke.py
- src/grid/molgrid.py
- src/grid/tests/test_molgrid.py
Fixes #48 
These are the least invasive changes that fix the problem, i.e. by manually chunking before running the vectorized code and by adding a few del statements to Python's garbage collector.
The performance overhead on my test case is about 7%. Performance can be improved by using dask to parallelize over chunks but I did not want to add dask as a dependency.
> Reduce memory usage of the becke weights

- src/grid/onedgrid.py
- src/grid/tests/test_onedgrid.py
I wrote some modifications in onedgrid and test_onedgrid so that these functions return a grid which is suited to approximate the integral of f(x) and not f(x)*w(x) where w(x) is the weight function associated to the quadrature (x^alpha * e^(-x) for Gauss Laguerre and 1/sqrt(1 - x^2) for Gauss Chebyshev).
> Modifications of GaussLaguerre and GaussChebyshev functions

- README.md
This is a minor fix taken from https://github.com/theochem/iodata/commit/938a0c58333c6be55ee59cc92efb01d5f17ffd92.
> Fix small terminology issue in acknowledgements

- src/grid/molgrid.py
1. This makes weight attr contain the total integration weight.
2. MolGrid can now use integrate method of Grid class.
3. AtomicGrid weights are still stored in _atweights attr.
> Make MolGrid weights consistent with Grid class

- src/grid/basegrid.py
- src/grid/molgrid.py
- src/grid/tests/test_grid.py
A bunch of unit tests were added to make sure get_subgrid works as expected in various scenarios.
I've also remove self._size and the way it was used in MolGrid. Constructors of subclasses should not use or change attributes defined by the parent class.
> Improve docstring of grid base class and improve get_subgrid

- src/grid/periodicgrid.py
- src/grid/tests/test_periodicgrid.py
I took some time to explain in detail how it worked in the docstrings. It would be good to check if they are sufficiently accessible.
I've relied on pytest features to write exhaustive unit tests. They will not run without pytest.
I've also checked if this can be used to partition electron densities of periodic systems. That all seems to work.
> PeriodicGrid class with support for periodic boundaries

- src/grid/basegrid.py
- src/grid/molgrid.py
- src/grid/periodicgrid.py
- src/grid/tests/test_grid.py
- src/grid/tests/test_molgrid.py
- src/grid/tests/test_periodicgrid.py
Fixes #93.
The function get_subgrid can return larger grids than the original one in case of periodic grids, typically when the cutoff sphere contains multiple unit cells. The resulting grid is therefore not necessarily a "sub"grid. This function does always make a local grid, centered around some piont, making "local"grid is more appropriate.
In some cases, the term subgrid was used in another context, e.g. for an atomic grid in a molecular grid. These were not renamed.
At the momemt, the following renamings were done:
- `subgrid` -> `localgrid`
- `subfn` -> `localfn`
- `SubGrid` -> `SubGrid`
and a few variants of these. One could argue that the first two would look better with an underscore after `local`.
> Rename Sub to Local, to better reflect code behavior

- src/grid/lebedev.py
This is a very minor change. Unless there is a specific reason to keep both dictionaries, I think it is less error-prone to build one from the other. Feel free to let me know what you think.
> Build LEBEDEV_DEGREES from LEBEDEV_NPOINTS

- src/grid/becke.py
- src/grid/tests/test_becke.py
1. For most atoms, if nan given, automatically select
atomic radius with 1 less.
`warning`: No.86 RN will still be broken.
> Add a condition to fix nan in noble gas atoms #100

- src/grid/atomgrid.py
- src/grid/molgrid.py
- src/grid/tests/test_atomgrid.py
- src/grid/tests/test_molgrid.py
Changs in `AtomGrid`
1. Set `rgrid` optional
2. Set `atnum` and `preset` to kwargs only
> Add kwargs to preset for a more user friendly API

- src/grid/molgrid.py
- src/grid/ode.py
- src/grid/onedgrid.py
- src/grid/rtransform.py
- src/grid/tests/test_atomgrid.py
- src/grid/tests/test_interpolate.py
- src/grid/tests/test_molgrid.py
- src/grid/tests/test_ode.py
- src/grid/tests/test_onedgrid.py
- src/grid/tests/test_poisson.py
- src/grid/tests/test_radial.py
- src/grid/tests/test_rtransform.py
- src/grid/tests/test_transform.py
This pull-request refactors (mostly documentation fixes) for onedgrid.py and rtransform.py.  
Key changes are:
- Added type hinting
- Changed the documentation in both files by fixing typos, adding equations, some references.
- Made it more explicit as to which intervals it's being mapped to in the documentation.
- Fixed flake8 and black issues
- cfcffc214e528b22ef7331ad9b541572c9c9a875 For Trefethen transformation in onedgrid.py, I made it more explicit that the d parameter is the degree of the Taylor polynomial of sin^{-1} and changed it so that it matches the equations, i.e. d=1 is identity, d=3 is the third degree etc. See the paper in [dropbox](https://drive.google.com/drive/folders/1ZBL50iFLchFspMYMcaNon_5seCrWAYua).
- da8509e685df865a5a0e6a0383dc1a39c7b63f8e Changed the naming of …
> Refactor documentation in onedgrid and rtransform

- src/grid/interpolate.py
- src/grid/lebedev.py
- src/grid/tests/test_interpolate.py
- src/grid/tests/test_lebedev.py
This pull request mostly improves the documentation in lebedev.py and interpolate.py modules.
Added couple tests in lebedev (a7b2b36fe97b701b7f9a650f51a3da9576f88673) and interpolate (aabffa92053e4fa15fe3efb262a25b8d6e961c46).  The commit headers should be clear which documentation were being changed.   Black and flake8 problems were fixed and type hinting was added.
> Improve documentation in lebedev.py and interpolate.py

- src/grid/ode.py
- src/grid/poisson.py
- src/grid/tests/test_ode.py
- src/grid/tests/test_poisson.py
This pull-requests refactors ode.py and makes a decent amount of changes.
Features
------------
- Remove the class structure and turn everything into functions (39372cb6d6e88bf2dd0d92fedd78410653df6d9a).
- Improve the documentation with formulas for all functions 
- Add the ability for the user to add their own initial guess and change the max_nodes in scipy.integrate.solve_bvp. This was to make sure the boundaries were satisfying the constraint for more accuracy.
- The code only supported transforming three order ODE, added the ability to transform higher orders (f5ceb2149a6a26cc057b8e621aef12ff664b9166)
- Changed it so that the solution to the ODE when using a transformation to a new coordinate is with respect to the old coordinate rather than the new coordinate.  This also converts …
> Refactor ode

- src/grid/atomgrid.py
- src/grid/tests/test_atomgrid.py
- src/grid/tests/test_utils.py
- src/grid/utils.py
This pull request adds the spherical average of a function in AtomGrid class.  It returns a splines that takes in radial points.
The tests that are included are:
- The spherical average of a Gaussian is itself and its integral (with 4 pi r^2) of the spherical average function is the integral of the Gaussian (pi^1.5)
- The spherical average of a Spherical Harmonic (whose degree is less than the degree of the atom grid) is zero.
> Spherical average

- src/grid/rtransform.py
- src/grid/tests/test_rtransform.py
Generalize radial transformations specific to HortonGrids/UniformInteger Grids. Specific to issue #143. 
The following grids were generalized to work over any grid:
- ExpRTransform
- LinearInfiniteRTransform
- PowerRTransform
The following grid wasn't generalized because it requires some assumptions on the parameters and is very heavy parameter fiddling
- HyperbolicRTransform.
> Generalize Some Radial Transformations

- src/grid/atomgrid.py
Relocated examples to Jupyter notebooks in another PR, making them redundant in the docstrings.
> Remove redundant examples atomgrid from docstrings

- examples/Angular_grid.ipynb
- examples/Atom_Grid.ipynb
- examples/Atom_Grid_Construction.ipynb
- examples/Cubic_Grids.ipynb
- examples/Interpolation_and_Poisson.ipynb
- examples/JCP_Paper.ipynb
- examples/Molecular_Grid.ipynb
- examples/Molecular_Grid_Construction.ipynb
- examples/Multipole_Moments.ipynb
- examples/One_dimensional_grids.ipynb
- examples/Quickstart.ipynb
@Ali-Tehrani HTML-style hyperlinks are not supported by nbsphinx so the google-colab badges don't work when rendered in the readthedocs pages. This PR provides a Fix for that. The solution is taken from https://github.com/QData/TextAttack/issues/244#issuecomment-674476435
One question:
Should we make an "Installation" notebook (separated from the paper notebook) so that we have a "complete" tutorial?
> Fix colab badges

- src/grid/cubic.py
- src/grid/poisson.py
- src/grid/tests/test_angular.py
- src/grid/tests/test_atomgrid.py
- src/grid/tests/test_becke.py
- src/grid/tests/test_cubic.py
- src/grid/tests/test_molgrid.py
- src/grid/tests/test_ode.py
- src/grid/tests/test_onedgrid.py
- src/grid/tests/test_periodicgrid.py
- src/grid/tests/test_poisson.py
- src/grid/tests/test_utils.py
- src/grid/utils.py
This pull-requests fixes:
- that pytest removed the option to capture warnings via None, this gives an error when using Python 3.11, see [here](https://github.com/scikit-learn/scikit-learn/issues/22572) and the our pull-request that failed recently #228.  This is heavily used in `test_periodic`, 
- Further `Nose` is used in periodic and is removed by me due to reasons specified by [pytest](https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose).
- Handles all warnings given in all of the tests. This handles issue #208. 
- For the UserWarnings, I used `pytest.warn(match=)` to make sure the warnings were raised. 
- In cases, where the warnings were coming from other modules I ignored them use the decorator `@pytest.mark.filterwarnings("ignore:api v1")` to …
> Fix raising warnings and pytest depreciation (#208)

- src/grid/angular.py
- src/grid/poisson.py
@Ali-Tehrani These are small fixes to @FarnazH fixes. The branch was merged before I could push them.
> Improve comments and remove Poisson example

- doc/index.rst
- src/grid/angular.py
- src/grid/atomgrid.py
- src/grid/tests/test_angular.py
Please see the commits and let me know if you have any questions.
> Fix Optional Arguments

- src/grid/__init__.py
- src/grid/ngrid.py
- src/grid/tests/test_ngrid.py
Added module and class for generic N grid integrations. This class is the base framework and on top of it, some porcelain will be added for the coulomb-exchange integrals.
> General class for N body grid integrations

- src/grid/ngrid.py
- src/grid/tests/test_ngrid.py
Refactored the ngrid module to improve readability and add features.
- Added weights property which returns the weights for each argument combination (due to its combinatorial nature returns a generator)
- Added points property which returns the combinations of arguments (due to its combinatorial nature returns a generator). Each point is a tuple with several arrays, each array corresponds to an argument of the multigrid function to integrate.
- Added support for non-vectorized functions. These will be evaluated point by point during the integration.
@PaulWAyers I think this PR improved the previous class. Nonetheless, I still have some doubts:
1. The current class used is a derived class of `Grid` because of this, several methods are inherited `moments`, `save` and `get_localgrid`. I …
> Refactor ngrid
